# This is a basic workflow to help you get started with Actions

name: Build gccgo12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: alpine:3.16
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: apk update && apk add git make gcc g++ libc-dev linux-headers python3

